// task07/src/app/calc/calc.component.ts
import {
  Component,
  OnInit
} from '@angular/core';

@Component({
  selector: 'calc',
  styles: [``],
  templateUrl: './calc.component.html'
})
export class CalcComponent implements OnInit {

  public number = NaN;

  public input = '';

  public isEndangered = false;

  public nums = [];

  public total = '...';

  constructor() {
    this.generate();
  }

  public generate() {
    const numbers = [];
    let sum = 0;

    for (let i = 1; i < 10; i++) {
      const res = i * this.number;
      sum += res;
      numbers.push({ key: i, res, str: isNaN(res) ? '...' : res });
    }

    this.nums = numbers;
    this.total = isNaN(sum) ? '...' : sum.toString();
  }

  public process() {
    // tslint:disable-next-line:radix
    const inp = parseInt(this.input);
    const isNan = isNaN(inp);
    this.number = inp;
    this.generate();
    if (isNan) {
      this.isEndangered = true;
      this.input = '';
    }
  }

  public reset() {
    this.isEndangered = false;
    this.number = NaN;
    this.generate();
  }

  public ngOnInit() {
    console.log('hello `Calc` component');
  }
}

<div>
  <div class="row">
    <div class="col-11">
      <input
        type="text"
        placeholder="Enter integral number"
        id="ctl"
        class="form-control"
        [(ngModel)]="input"
        (keyup)="reset()"
      />
    </div>
    <div class="col-1"><button id="btn" [class.btn]="true" [class.btn-danger]="isEndangered" (click)="process()">Go!</button></div>
  </div>
  <hr />
  <div class="row">
    <div class="col-12">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Multiplier</th>
            <th>Result</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let num of nums">
            <th class="mul-{{num.key}}">{{num.key}}</th>
            <td class="res-{{num.key}}">{{num.str}}</td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <th>Total</th>
            <td>{{ total }}</td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

// task05/src/components/calc.tsx
import * as React from "react";
import { number } from "prop-types";

export interface CalcProps {
  placeholder: string;
  label: string;
}

export interface CalcState {
    value: string;
    number: number;
    classNames: string
  }

export class Calc extends React.Component<CalcProps, CalcState> {
  constructor(props: CalcProps) {
    super(props);

    this.state = { value: "", number: NaN, classNames: "btn" };

    this.change = this.change.bind(this);
    this.trigger = this.trigger.bind(this);
  }
  change(event: any) {
    const target = event.target;
    this.setState({ value: target.value, number: NaN, classNames: "btn" });
  }
  trigger(event: any) {
    const inp = parseInt(this.state.value);
    const isNan = isNaN(inp);
    this.setState({
      value: isNan ? "" : this.state.value,
      number: inp,
      classNames: "btn" + (isNan ? " btn-danger" : "")
    });
  }
  render() {
    let numbers: { key: number; res: number }[] = [];
    let total = 0;
    
    for (let i = 1; i < 10; i++) {
      const res = i * this.state.number;
      total += res;
      numbers.push({ key: i, res });
    }
    
    const body = numbers.map(num => 
      <tr key={num.key.toString()}>
        <th className={"mul-" + num.key}>{num.key}</th>
        <td className={"res-" + num.key}>{ isNaN(num.res) ? "..." : num.res }</td>
      </tr>
    );

    return (
      <div>
        <div className="row">
          <div className="col-11">
            <input
              type="text"
              placeholder={this.props.placeholder}
              id="ctl"
              className="form-control"
              value={this.state.value}
              onChange={this.change} 
            />
          </div>
          <div className="col-1">
            <button
              id="btn"
              className={this.state.classNames}
              onClick={this.trigger}
            >
              {this.props.label}
            </button>
          </div>
        </div>
        <hr />
        <div className="row">
          <div className="col-12">
            <table className="table table-striped">
              <thead>
                <tr>
                  <th>Multiplier</th>
                  <th>Result</th>
                </tr>
              </thead>
              <tbody>{body}</tbody>
              <tfoot>
                <tr>
                  <th>Total</th>
                  <td>{ isNaN(total) ? "..." : total }</td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    );
  }
}
